#+TITLE:     Daily Work Report
#+AUTHOR:    M.S.Soumya
#+EMAIL:     ms@ms
#+DATE:      2015-03-25 Wed

* [2015-03-24 Tue]
+ Finished writing the scripts using the hostnames and ip addresses as
  variables in the zone files(as asked by Saurabh).
+ Tried testing the scripts on my desktop on a container. Faced some
  network issues, which I couldn't resolve.
  - Tried to make the containers work in the existing setup on my
    desktop by cnnecting it to the bridges. 
  - Tried creating a new interface for the container and connecting it
    to the bridge, it still didnt work.
  - All these didnt work because the IP was not a part of that subnet.
+ Tested the scripts removing the ossec and rsyslog roles. The common
  roles was causing some problem, so I commented the common roles to
  test the execution of my scripts. They seem to work fine. Have to be
  reviewed by Saurabh.
** TODO Create a new folder called "aws2" and add the makefile and see that it works properly.
** TODO Start modelling the scripts written by Saurabh into a rough Literate version such that 
**      the code tangles properly in the right structure.
** TODO Collaborate with yogesh and siva to add in their models of the rsyslog server and the reverseproxy server.

