#+Title: Work Log of Yogesh Agrawal
#+Email: yogesh@vlabs.ac.in; yogeshiiith@gmail.com

* Year:: 2015

** Month:: March

*** Date:: 24 March 2015 Tuesday
1) Created document of procedure for hosting labs on base machines. Document is
   hosted on vlead-wiki server.
2) Reviewed reverseproxy server aws model created by Mr. Siva.

*** Date:: 25 March 2015 Wednesday
1) Contanct integration engineers of IIT-Kanpur regarding hosting of their labs
   in IIIT infrastrcture.
2) Once again review the aws model of reverseproxy with Mr. Siva.
3) Help Miss. Soumya in her work to structure aws repository properly.
4) Provide list of vlead engineers and their email ids to Mrs. Geeta.
5) Help Mr. Arnav to build threat model for vlead infrastructure.
6) Completed rsyslog aws model; test cases are to be implemented.

** TODO Update Ansible version to 1.8
** TODO Write description of common firewall rule and integrate with common role.
** TODO Write test cases for rsyslog server
** TODO Coordinate with soumya to move rsyslog_server.org to new repo structure.
** TODO Update virtual-labs.ac.in server with link of labs from IITK and Dayalbagh University.
** TODO Define common variables that are used by various other roles.
