#+PROPERTY: results output
#+PROPERTY: tangle ../build/roles/ansible/tasks/main.yml
#+PROPERTY: exports code
# Generated by iptables-save v1.4.7 on Fri Mar  6 06:11:26 2015
* Introduction 
This is a template which is inserted into the firewall rules of the
host machine which is being configured. The host machine being
configured is an ansible server. 

* Firewall rules
The ansible server has a set of firewall rules which are implemented
as under: 
- The basic contents of the firewall is as below:
#+BEGIN_SRC YAML
*filter
:INPUT ACCEPT [773:1200054]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [940:1161060]
#+END_SRC

- The ansible server needs to accept all connections from loop back. The
  firewall rule which suggests this is as below:
#+BEGIN_SRC YAML
#Accept all connections from loop-back
-A INPUT -i lo -j ACCEPT
#+END_SRC

- The server should allow the ongoing connections 
#+BEGIN_SRC YAML
#Allow ongoing connections
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
#+END_SRC

- The server should allow *only* the VLEAD network to ssh to it on port 22. The rule below configures the same:
#+BEGIN_SRC YAML
-A INPUT -p tcp -m tcp --dport 22 -s 10.0.0.0/8 -j ACCEPT
#+END_SRC

- The server should accept ICMP request
#+BEGIN_SRC 
-A INPUT -p icmp -m icmp --icmp-type echo-request -j ACCEPT
#+END_SRC

- The packets incoming or outgoing on other ports should be rejected. This rule is implemented by the following firewall rules:
#+BEGIN_SRC 
-A INPUT -j REJECT
-A FORWARD -j REJECT
COMMIT
#+END_SRC

# Completed on Fri Mar  6 06:11:26 2015
