
#+PROPERTY: session *scratch*
#+PROPERTY: results output
#+PROPERTY: tangle ../build/ansible.yml
#+PROPERTY: exports code

This script configures the ansible server according to the roles
given.. 

#+BEGIN_SRC YAML
---
- name: Configure ansible server
  hosts: ansible-server
  roles:
    - common
    - ansible
#+END_SRC

Here, we are using two roles as follows:

- common: the configuration defined inside this, is common to all
  servers. The organization is as follows:
  + meta: This has =main.yml= and all the role dependencies are listed
    in this.
  + tasks: =main.yml= inside this ensures that common iptables for all
    server are included.
  + handlers: The =main.yml= inside handlers notifies it what services need to be restarted, if that action(change) is performed.

- ansible: this configuration is specific to ansible server.
 The organization of configuration inside these roles is as follows:
  + meta: This has =main.yml= and all the role dependencies are listed
    in this.
  + tasks: =main.yml= inside this ensures that iptables for ansible
    server are included.
  + handlers: The =main.yml= inside handlers notifies it what services need to be restarted, if that action(change) is performed.
